server:
  port: 8080

application:
  name: @project.name@
  description: @project.description@
  version: @project.version@

spring:
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_rotten_itaumatoes?createDatabaseIfNotExist=true&connectionTimeZone=UTC"
    username: "root"
    password: "root"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: "update"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

feign:
  config:
    omdb:
      apiKey: "edf0a411"
      url: "http://www.omdbapi.com"
    authServer:
      url: "http://localhost:8081"

security:
  hash:
    loops: 100000
    keyLength: 256
    salt: -80,88,10,39,125,-71,-1,0,53,-112,-67,88,7,15,95,-110
    algorithm: "PBKDF2WithHmacSHA1"
  jwt:
    secret: "bVps6IafGVXz5OeLBuBbBQYctOcjT70BG2hEjeRuJ3Hgpnti1f6uAkA3EM4ZxaV"
